### PR TITLE
Check binary path of PID lock

### LINKED ISSUE #230: Portmaster Core is already running but the PID is systemd-machined
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

All I've changed since last reboot (used Windows for 3 days) was masking dnsmasq because it prevented portmaster from starting so I always had to `killall dnsmasq && systemctl restart portmaster` after system startup to fix DNS. Today It didn't work and portmaster complains about it is already running at PID 918 which is actually a systemd service.

```
» sudo systemctl status portmaster
● portmaster.service - Portmaster Privacy App
     Loaded: loaded (/etc/systemd/system/portmaster.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2021-01-11 18:17:35 CET; 4min 26s ago
    Process: 21143 ExecStart=/var/lib/portmaster/portmaster-start --data /var/lib/portmaster core (code=exited, status=1/FAILURE)
    Process: 21209 ExecStopPost=/sbin/iptables -F C17 (code=exited, status=1/FAILURE)
    Process: 21220 ExecStopPost=/sbin/iptables -t mangle -F C170 (code=exited, status=1/FAILURE)
    Process: 21221 ExecStopPost=/sbin/iptables -t mangle -F 171 (code=exited, status=1/FAILURE)
   Main PID: 21143 (code=exited, status=1/FAILURE)

Jan 11 18:17:35 northys-fedora systemd[1]: Started Portmaster Privacy App.
Jan 11 18:17:35 northys-fedora portmaster-start[21143]: Error: another instance of Portmaster Core is already running: PID 918
Jan 11 18:17:35 northys-fedora systemd[1]: portmaster.service: Main process exited, code=exited, status=1/FAILURE
Jan 11 18:17:35 northys-fedora iptables[21209]: iptables: No chain/target/match by that name.
Jan 11 18:17:35 northys-fedora iptables[21220]: iptables: No chain/target/match by that name.
Jan 11 18:17:35 northys-fedora iptables[21221]: iptables: No chain/target/match by that name.
Jan 11 18:17:35 northys-fedora systemd[1]: portmaster.service: Failed with result 'exit-code'.


» sudo /var/lib/portmaster/portmaster-start --data /var/lib/portmaster core
Error: another instance of Portmaster Core is already running: PID 918


» sudo ps faxu | grep 918
root         918  0.0  0.0  18988  6232 ?        Ss   16:56   0:00 /usr/lib/systemd/systemd-machined
northys    25207  0.0  0.0 216084   648 pts/2    S+   18:22   0:00  |   |       \_ grep --color=auto 918


» sudo /var/lib/portmaster/portmaster-start version
Portmaster Start
version 0.5.0

commit tags/v0.6.0-0-g454a234449dd27930ca9c68458502ac9605b9f9b
built with go1.14.2 (gc) linux/amd64
  using options 
  by user@docker
  on 24.11.2020

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

**What you expected to happen**:

Regardless the problem I have with dnsmasq it is weird that portmaster is already running at systemd-machined's PID.

**How to reproduce it (as minimally and precisely as possible)**:

I wasn't able to replicate it by masking dnsmasq using `systemctl mask dnsmasq`.

~~All I remember is running `systemctl mask dnsmasq` on my Fedora 32.~~

~~I'm [using portmaster.service from wiki](https://github.com/safing/portmaster/wiki/Linux).~~
```
» sudo systemctl cat portmaster
# /etc/systemd/system/portmaster.service
[Unit]
Description=Portmaster Privacy App

[Service]
Type=simple
User=root
Group=root
ExecStart=/var/lib/portmaster/portmaster-start --data /var/lib/portmaster core
ExecStopPost=-/sbin/iptables -F C17
ExecStopPost=-/sbin/iptables -t mangle -F C170
ExecStopPost=-/sbin/iptables -t mangle -F 171

[Install]
WantedBy=multi-user.target
```
~~

**Anything else we need to know?**:

**Environment**:

Portmaster Version: 

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux

```
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### PR DESCRIPTION
**Pull request by dhaavi**
Fixes #230.

Heads up! Requires change in `portbase/utils/atomic.go`:
```
	// Version is fixed to commit 353f8196982447d8b12c64f69530e657331e3dbc.
	// The follow-up commit removes Windows support.
	// TOOD: Check how we want to handle this in the future, possibly ingest
	// needed functionality into here.
	"github.com/google/renameio"
```

Will be committed with all the updated go.mod files.

### CODE REVIEW

File: cmds/portmaster-start/lock.go [hunk 1]
```diff
@@ -32,14 +32,42 @@ func checkAndCreateInstanceLock(name string) (pid int32, err error) {
...
-	// check if process exists
+	// Check if process exists.
 	p, err := processInfo.NewProcess(int32(parsedPid))
-	if err == nil {
-		return p.Pid, nil
+	if err != nil {
+		// A process with the locked PID does not exist.
+		// This is expected, so we can continue normally.
+		return 0, createInstanceLock(lockFilePath)
+	}
```
Comment (ppacher) [inline cmds/portmaster-start/lock.go:41]: Use `errors.Is(err, processInfo.ErrorProcessNotRunning` as we might have a different error here as well. I.e. `PermissionDenied`.

File: cmds/portmaster-start/lock.go [hunk 2]
```diff
@@ -32,14 +32,42 @@ func checkAndCreateInstanceLock(name string) (pid int32, err error) {
...
+		return 0, fmt.Errorf("failed to evaluate path of own process: %w", err)
+	}
+
+	// Check if the binary path matches.
+	if cleanedExecutingBinaryPath != cleanedOwnBinaryPath {
+		// The process with the locked PID belongs to another binary.
+		// As the Portmaster usually starts very early, it will have a low PID,
+		// which could be assigned to another process on next boot.
+		return 0, createInstanceLock(lockFilePath)
 	}
```
Comment (ppacher) [inline cmds/portmaster-start/lock.go:67]: I would remove the part with the "low PID" because it doesn't really matter. If we failed to cleanup our PID file we may have the situtation even if the PID is very high

**Review by ppacher — CHANGES_REQUESTED** [review]
IMHO we still don't know how the PID lock file could have survived. PM-start should not allow this to happen ...

File: cmds/portmaster-start/lock.go (hunk 2 above)
Comment (dhaavi) [reply cmds/portmaster-start/lock.go:67]: We have experienced this issue on both Linux and Windows now. I think we already do everything right with the cleaning up. But apparently, that is not enough.

**Review by ppacher — APPROVED** [review]
